### ISSUE TITLE
/sys should be writeable

### ISSUE THREAD

**Issue by amshinde** [clearcontainers/agent#163]
I have seen issues with unbinding a device from its driver and assigning it to another driver, because  sysfs is read-only. I am also not able to change any module parameters as well.
Gives this error:

bash: /sys/module/.............: Read-only file system

I need to explicitly do this:
mount -o remount,rw /sys

I think we should mount sysfs as read-write in our agent.

**Comment by sboeuf** [comment]
Yes, this makes sense. You should try to modify this line https://github.com/clearcontainers/agent/blob/master/agent.go#L1176
This should do the trick :)
