### ISSUE TITLE
Route table not setup properly for PTP CNI plugin

### ISSUE THREAD

**Issue by mcastelino** [clearcontainers/agent#175]
For full details

https://github.com/containers/virtcontainers/issues/500

**Comment by mcastelino** [comment]
@amshinde the best option would be to delete the conflicting route and add the new one if we see conflict.

**Comment by amshinde** [comment]
@mcastelino Agree, that seems like the best option to handle this.

**Comment by mcastelino** [comment]
@amshinde for now :) Later we need to implement a wipe and update.
