### ISSUE TITLE
Revert the reaper fix since it has been fixed in libcontainer

### ISSUE THREAD

**Issue by sboeuf** [clearcontainers/agent#79]
This needs some investigations and tests, but I think that libcontainer has been fixed by https://github.com/opencontainers/runc/pull/1506 and that we don't need this commit anymore https://github.com/clearcontainers/agent/commit/56aca9119aa6d181b7e9660e93e9343a53072fd1

**Comment by egernst** [comment]
@sboeuf - should your PR reference this?  or, is this a duplicate that can  be closed?

**Comment by sboeuf** [comment]
duplicate that can be closed.
