### ISSUE TITLE
9p mount fails for certain workloads

### ISSUE THREAD

**Issue by egernst** [clearcontainers/agent#92]
This is based on the errors observed with 9p on the 2.x release.  

See https://github.com/01org/cc-oci-runtime/issues/320 and 
https://github.com/01org/cc-oci-runtime/issues/949

From Arindam's debug, we understand the root cause as follows:

```
By default, 9pfs provides readonly mmap. Meaninig:
open("/tmp/.rte_config", O_RDWR|O_CREAT, 0660) with RDWR flag, and then a consequent mmap with any value will fail.
Reason: generic_file_readonly_mmap is used by 9pfs Kernel side client code, in case there is no caching.

How to avoid this:
For Guest OS, ensure CONFIG_9P_FSCACHE is enable.
Everything else remaining the same, the mount command in the guest OS should looks something like this:
mount -t 9p -o trans=virtio test_mount /tmp/shared/ -oversion=9p2000.L,posixacl,cache=[loose or mmap or fscache]
Then instead of generic_file_readonly_mmap, v9fs_file_mmap is used, which allows mmaping with write capabilities.
```

I've tested with 3.0 by updating the guests' kernel and updating the agent to append the specified mount command line options.  I'd like to see that this is tested for performance impact, though I think it is critical that we are functional vs performant.

An easy test case for this is to try to run the testpmd application inside of a container.  See egernst/dpdk-enabled-ubuntu.

**Comment by egernst** [comment]
After running through performance testing, I plan to use mmap instead of fscache.

**Comment by egernst** [comment]
reopening since the original patch was reverted due to some observed instability in the CI system.

@rarindam  you mentioned "if using vhost9p, fsdev option needs to be removed"

In fact, we are using virtio-9p in our setup.  Example:
QEMU commandline:
```  
-device virtio-9p-pci,fsdev=ctr-9p-0,mount_tag=ctr-rootfs-0
-fsdev local,id=ctr-9p-0,path=/var/lib/docker/aufs/mnt/0cd5e771f769249ff79baaea27a52171f8e7e766d86c228b7a4967dd5395b5e5,security_model=none
-device virtio-9p-pci,fsdev=extra-9p-hyperShared,mount_tag=hyperShared
-fsdev local,id=extra-9p-hyperShared,path=/tmp/hyper/shared/pods/4055d2041a5d264cd05c5d1d49172017acd5400e211c4d6276b60cc14ef3143b,security_model=none
```

In the guest (with no caching enabled):
```
/ # mount | grep 9p
hyperShared on / type 9p (rw,sync,dirsync,nodev,relatime,trans=virtio,version=9p2000.L,posixacl,cache=none)
hyperShared on /etc/resolv.conf type 9p (rw,sync,dirsync,nodev,relatime,trans=virtio,version=9p2000.L,posixacl,cache=none)
hyperShared on /etc/hostname type 9p (rw,sync,dirsync,nodev,relatime,trans=virtio,version=9p2000.L,posixacl,cache=none)
hyperShared on /etc/hosts type 9p (rw,sync,dirsync,nodev,relatime,trans=virtio,version=9p2000.L,posixacl,cache=none)
```

**Comment by rarindam** [comment]
Please attach any logs possible.

On Sep 1, 2017, at 6:58 AM, Eric Ernst <notifications@github.com<mailto:notifications@github.com>> wrote:


reopening since the original patch was reverted due to some observed instability in the CI system.

@rarindam<https://github.com/rarindam> you mentioned "if using vhost9p, fsdev option needs to be removed"

In fact, we are using virtio-9p in our setup. Example:
QEMU commandline:

-device virtio-9p-pci,fsdev=ctr-9p-0,mount_tag=ctr-rootfs-0
-fsdev local,id=ctr-9p-0,path=/var/lib/docker/aufs/mnt/0cd5e771f769249ff79baaea27a52171f8e7e766d86c228b7a4967dd5395b5e5,security_model=none
-device virtio-9p-pci,fsdev=extra-9p-hyperShared,mount_tag=hyperShared
-fsdev local,id=extra-9p-hyperShared,path=/tmp/hyper/shared/pods/4055d2041a5d264cd05c5d1d49172017acd5400e211c4d6276b60cc14ef3143b,security_model=none


In the guest (with no caching enabled):

/ # mount | grep 9p
hyperShared on / type 9p (rw,sync,dirsync,nodev,relatime,trans=virtio,version=9p2000.L,posixacl,cache=none)
hyperShared on /etc/resolv.conf type 9p (rw,sync,dirsync,nodev,relatime,trans=virtio,version=9p2000.L,posixacl,cache=none)
hyperShared on /etc/hostname type 9p (rw,sync,dirsync,nodev,relatime,trans=virtio,version=9p2000.L,posixacl,cache=none)
hyperShared on /etc/hosts type 9p (rw,sync,dirsync,nodev,relatime,trans=virtio,version=9p2000.L,posixacl,cache=none)

**Comment by rarindam** [comment]
What was the instability?

**Comment by egernst** [comment]
@rarindam -- looking at the logs, when I have either fscache or mmap, the instability happens around removal of the container:

ex1: from http://cc-jenkins-ci.westus2.cloudapp.azure.com/view/Ubuntu_16.04/job/clear-containers-agent-azure-ubuntu-16-04/15/console --> cache=mmap
```
15:22:00 [91m[1mSummarizing 6 Failures:[0m
15:22:00 
15:22:00 [91m[1m[Fail] [0m[90mdocker kill [0m[0mkilling container [0m[91m[1m[It] with '6' signal [0m
15:22:00 [37m/home/jenkins/go/src/github.com/clearcontainers/tests/integration/docker/kill_test.go:91[0m
15:22:00 
15:22:00 [91m[1m[Fail] [0m[90mdocker kill [0m[0mkilling container [0m[91m[1m[It] with '10' signal [0m
15:22:00 [37m/home/jenkins/go/src/github.com/clearcontainers/tests/integration/docker/kill_test.go:91[0m
15:22:00 
15:22:00 [91m[1m[Fail] [0m[90mdocker kill [0m[0mkilling container [0m[91m[1m[It] with '20' signal [0m
15:22:00 [37m/home/jenkins/go/src/github.com/clearcontainers/tests/integration/docker/kill_test.go:91[0m
15:22:00 
15:22:00 [91m[1m[Fail] [0m[90mdocker kill [0m[0mkilling container [0m[91m[1m[It] with '21' signal [0m
15:22:00 [37m/home/jenkins/go/src/github.com/clearcontainers/tests/integration/docker/kill_test.go:91[0m
15:22:00 
15:22:00 [91m[1m[Fail] [0m[90mdocker kill [0m[0mkilling container [0m[91m[1m[It] with '27' signal [0m
15:22:00 [37m/home/jenkins/go/src/github.com/clearcontainers/tests/integration/docker/kill_test.go:91[0m
15:22:00 
15:22:00 [91m[1m[Fail] [0m[90mdocker kill [0m[0mkilling container [0m[91m[1m[It] with '29' signal [0m
15:22:00 [37m/home/jenkins/go/src/github.com/clearcontainers/tests/integration/docker/kill_test.go:91[0m
```

Another failure example observed from http://cc-jenkins-ci.westus2.cloudapp.azure.com/view/Ubuntu_16.04/job/clear-containers-agent-azure-ubuntu-16-04/14/consoleFull --> cache=fscache
```
15:06:03 # time="2017-09-01 15:06:02.546670728Z" level=debug msg="Caught SIGTERM" 
15:06:03 # time="2017-09-01 15:06:03.566013331Z" level=info msg="error shutting down layer storage: device or resource busy" 
15:06:03 # 0
15:06:03 # rm: cannot remove '/tmp/tmp.6t0sXYeZtV/crio/aufs': Device or resource busy
15:06:18 not ok 5 ctr lifecycle
15:06:18 # (from function `cleanup_test' in file helpers.bash, line 336,
15:06:18 #  from function `teardown' in test file crio.bats, line 20)
15:06:18 #   `cleanup_test' failed
```

**Comment by egernst** [comment]
I'll look to get a more focused test going, but all of the failures I've seen so far deal with tearing down the container / shutting down the filesystem.
